apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vllm.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  {{- with .Values.deploy.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.deploy.replicaCount }}
  selector:
    matchLabels:
      {{- include "vllm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deploy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vllm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deploy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deploy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deploy.securityContext | nindent 12 }}
          image: "{{ .Values.deploy.image.repository }}:{{ .Values.deploy.image.tag }}"
          imagePullPolicy: {{ .Values.deploy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deploy.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 60
            httpGet:
              path: /health
              port: {{ .Values.deploy.port }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 60
            httpGet:
              path: /health
              port: {{ .Values.deploy.port }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.deploy.resources | nindent 12 }}
          env:
            {{- with .Values.deploy.env -}}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          args:
            - --port
            - {{ .Values.deploy.port | quote }}
          {{- with .Values.deploy.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}  
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          {{- with .Values.deploy.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            {{- if .Values.deploy.pvcCache.enabled }}
            - name: {{ include "vllm.fullname" . | quote }}
              mountPath: {{ .Values.deploy.pvcCache.cachePath | quote }}
            {{- end }}
      volumes:
        - name: dshm
          emptyDir:
             medium: Memory
        {{- if .Values.deploy.pvcCache.enabled }}
        - name: {{ include "vllm.fullname" . | quote }}
          persistentVolumeClaim:
            claimName: {{ include "vllm.fullname" . | quote }}
        {{- end }}
        {{- with .Values.deploy.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deploy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}